### ISSUE TITLE
`sessions.messages.subscribe` not supported by OpenClaw gateway — streaming fails with v0.3.0 client

### ISSUE THREAD

**Issue by longfin** [planetarium/vicoop-bridge#61]
## Environment
- vicoop-bridge-client: v0.3.0
- Backend: openclaw
- OpenClaw version: 2026.3.13
- OpenClaw gateway: ws://127.0.0.1:3000

## Problem
After upgrading to v0.3.0, the client repeatedly logs:

[openclaw] sessions.messages.subscribe failed for agent:main:<session-id>: unknown method: sessions.messages.subscribe (continuing without streaming)

The v0.3.0 client attempts to subscribe to streaming via `sessions.messages.subscribe` on the OpenClaw gateway WebSocket, but the current OpenClaw version does not implement this method.

## Impact
- Streaming falls back gracefully per the log message, so basic message/send works
- However, `message/stream` requests from A2A inspector return a Content-Type mismatch error (`Expected text/event-stream, got application/json`)
- The agent card now advertises `streaming: true` by default in v0.3.0, which mismatches actual capability

## Possible fix
- Document which OpenClaw gateway version is required for streaming support in v0.3.0
- Or allow `streaming: false` card override when gateway doesn't support `sessions.messages.subscribe`

**Comment by longfin** [comment]
Investigated upstream — `sessions.messages.subscribe` was introduced in OpenClaw PR #50101 (commit 7b61ca1b, 2026-03-19). First tags that include it:

- v2026.3.22-beta.1 (2026-03-23) — first appearance
- v2026.3.22 (2026-03-23) — first stable

Reporter's v2026.3.13 is ~9 days older than this method, so the `unknown method` error is expected.

Minimum OpenClaw version required for v0.3.0 streaming: **v2026.3.22**.

Planned fix:
- Document min OpenClaw version (`docs/install-client.md`, README).
- Keep graceful subscribe-failure fallback as-is, but also downgrade the advertised card capability to `streaming: false` when the gateway rejects `sessions.messages.subscribe`, so A2A callers don't ask for `message/stream` against a backend that can't deliver it.

**Comment by longfin** [comment]
Investigated whether an alternative implementation that avoids `sessions.messages.subscribe` is feasible for older gateways (v2026.3.13 and earlier).

**Short answer: no push-based equivalent exists on those versions.**

Breakdown of the options considered (against v2026.3.13 source):

1. **Reuse the existing `chat` event** — not viable. `broadcastChatFinal`/`broadcastChatError` only emit `state: "final"`/`"error"`. Intermediate assistant messages are never pushed to operator connections. PR #56's constraint ("true per-token deltas unreachable from `role:\"operator\"`") applies equally to older versions.

2. **`chat.history` polling workaround** — technically possible (the method exists in v2026.3.13), but adds polling latency, gateway RPC load, and a nontrivial race against the terminal `chat:final` event. It reinvents what `sessions.messages.subscribe` does natively. Not worth the complexity.

3. **Switch from `role:"operator"` to `role:"node"`** — `role:"node"` targets the device-pairing/canvas subsystem with very different scope semantics, not a drop-in substitute for bridge-client.

4. **Upstream patch (`chat.send` registers a `clientRunId` for operators)** — would unblock true per-token deltas, but requires an OpenClaw PR and still produces a minimum-version requirement. Same shape as today's situation.

**Conclusion:** there is no clean way to deliver in-progress message-boundary streaming on operator connections without `sessions.messages.subscribe`. For gateways that lack it, the realistic choice is:

- **(a)** Advertise `streaming: false`, keep the existing runtime fallback (single terminal artifact). Simple, matches reality.
- **(b)** Fake it with `chat.history` polling. Higher complexity, worse UX than native push.

Going with (a): PR incoming that probes the gateway at connect time and registers the A2A card with `capabilities.streaming` set according to actual gateway capability — so new gateways keep advertising streaming, old gateways advertise non-streaming automatically.
