### PR TITLE
Probe OpenClaw gateway and downgrade streaming capability for pre-v2026.3.22

### LINKED ISSUE #61: `sessions.messages.subscribe` not supported by OpenClaw gateway — streaming fails with v0.3.0 client
## Environment
- vicoop-bridge-client: v0.3.0
- Backend: openclaw
- OpenClaw version: 2026.3.13
- OpenClaw gateway: ws://127.0.0.1:3000

## Problem
After upgrading to v0.3.0, the client repeatedly logs:

[openclaw] sessions.messages.subscribe failed for agent:main:<session-id>: unknown method: sessions.messages.subscribe (continuing without streaming)

The v0.3.0 client attempts to subscribe to streaming via `sessions.messages.subscribe` on the OpenClaw gateway WebSocket, but the current OpenClaw version does not implement this method.

## Impact
- Streaming falls back gracefully per the log message, so basic message/send works
- However, `message/stream` requests from A2A inspector return a Content-Type mismatch error (`Expected text/event-stream, got application/json`)
- The agent card now advertises `streaming: true` by default in v0.3.0, which mismatches actual capability

## Possible fix
- Document which OpenClaw gateway version is required for streaming support in v0.3.0
- Or allow `streaming: false` card override when gateway doesn't support `sessions.messages.subscribe`

### PR DESCRIPTION
**Pull request by longfin**
Closes #61.

## Problem

The v0.3.0 client bumped `capabilities.streaming` from `false` to `true`, backed by the `sessions.messages.subscribe` RPC. That RPC was added in OpenClaw **v2026.3.22** (upstream PR `openclaw/openclaw#50101`); earlier gateways accept the same wire protocol (v3) but reject the call with `unknown method: sessions.messages.subscribe`.

Today the client handles that error gracefully at runtime (single final artifact, no streaming), but the advertised card still lies — A2A callers that honor the card and issue `message/stream` end up with a content-type mismatch. Reporter of #61 is on v2026.3.13 and sees this.

See the issue for the upstream release archaeology and the alternative-implementation review (no non-`sessions.messages.subscribe` push path exists on older gateways).

## Approach

Option (a) from the issue discussion: **don't try to support streaming on pre-v2026.3.22 gateways, but make the downgrade automatic and correct.**

- Add optional `Backend.resolveCapabilities()` — called once at startup, before the bridge-server `hello` frame.
- OpenClaw backend sends `sessions.messages.subscribe` with a synthetic sessionKey and decides from the response:
  - success → `streaming: true` (best-effort unsubscribe cleanup).
  - `unknown method` error → `streaming: false` + one-line downgrade warning.
  - any other error (scope, invalid key, …) → `streaming: true` (method dispatched, just rejected).
  - gateway unreachable → `{}` (no override; card value wins — transient outages shouldn't spuriously downgrade healthy deployments).
- `Client` awaits the probe and merges detected capabilities into the card. Result is cached for the process lifetime so bridge reconnects don't re-probe.
- Document the minimum gateway version in `docs/install-client.md`.
- Bump client to 0.3.1.

## Test plan

- [x] `pnpm -r typecheck` clean
- [x] `pnpm --filter @vicoop-bridge/client test` — 49/49 passing (4 new `resolveCapabilities` tests covering supported / unknown-method / non-method-error / unreachable paths)
- [x] `pnpm --filter @vicoop-bridge/client build` clean
- [ ] Manual E2E against a v2026.3.13 gateway (optional; probe logic is covered by the unit tests that replay the exact `unknown method` shape)
- [ ] Manual E2E against a v2026.3.22+ gateway (streaming should remain advertised and delivered)

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

File: packages/client/src/client.ts [hunk 1]
```diff
@@ -37,19 +43,57 @@ export class Client {
...
+      this.resolveEffectiveCard().then((agentCard) => {
+        if (ws.readyState !== WebSocket.OPEN) return;
+        console.log('[client] connected, sending hello');
+        this.send({
+          type: 'hello',
+          agentId: this.opts.agentId,
+          agentCard,
+          version: PROTOCOL_VERSION,
+          token: this.opts.token,
+        });
```
[the remark this answers is not in the document]
Comment (longfin) [reply packages/client/src/client.ts]: Fixed — swapped `this.send({...})` for `ws.send(encodeFrame({...}))` on the captured socket, so the readyState guard and the send target reference the same `ws` instance even if a reconnect swaps `this.ws` during the probe's async gap. Pushed in 5a20765.

File: packages/client/src/client.ts [hunk 2]
```diff
@@ -37,19 +43,66 @@ export class Client {
...
+        ws.send(
+          encodeFrame({
+            type: 'hello',
+            agentId: this.opts.agentId,
+            agentCard,
+            version: PROTOCOL_VERSION,
+            token: this.opts.token,
+          }),
+        );
       });
```
[the remark this answers is not in the document]
Comment (longfin) [reply packages/client/src/client.ts]: Fixed — `Client.start()` now kicks off `resolveEffectiveCard()` before opening the bridge WS, so the probe runs in parallel with the bridge TCP/WS handshake and is nearly always done by the time `open` fires. Keeps hello well inside the server's 10s deadline even when the backend probe itself takes seconds. Pushed in d8cbf6c.

File: packages/client/src/client.ts [hunk 3]
```diff
@@ -37,19 +43,66 @@ export class Client {
...
+        const detected = await probe.call(this.opts.backend);
+        const merged: AgentCard['capabilities'] = {
+          ...(base.capabilities ?? {}),
+          ...(detected.streaming !== undefined ? { streaming: detected.streaming } : {}),
+          ...(detected.pushNotifications !== undefined
+            ? { pushNotifications: detected.pushNotifications }
+            : {}),
+        };
+        return { ...base, capabilities: merged };
+      } catch (err) {
```
[the remark this answers is not in the document]
Comment (longfin) [reply packages/client/src/client.ts]: Fixed — early-return the base card unchanged when `detected.streaming` and `detected.pushNotifications` are both undefined, so an absent `capabilities` field stays absent and the contract "`{}` = no override" holds. Pushed in d8cbf6c.

File: packages/client/src/backends/openclaw.ts [hunk 4]
```diff
@@ -906,6 +906,50 @@ export function createOpenclawBackend(
...
+      } catch (err) {
+        const msg = errorMessage(err);
+        if (/unknown method/i.test(msg)) {
+          console.warn(
+            '[openclaw] gateway does not implement sessions.messages.subscribe; advertising streaming:false (streaming requires OpenClaw >= v2026.3.22)',
+          );
+          return { streaming: false };
+        }
+        return { streaming: true };
+      }
```
[the remark this answers is not in the document]
Comment (longfin) [reply packages/client/src/backends/openclaw.ts:973]: Fixed — added a `gatewayLacksMessageSubscribe` latch in the backend closure. Set to true by either the startup probe or a per-task attempt the moment we see an `unknown method` response; `ensureSessionMessageSubscription` short-circuits when the latch is set, so subsequent tasks issue neither the RPC nor a warn log. The latch resets on gateway reconnect so an upgraded gateway restores streaming without a client restart. Added a test that drives two tasks after the verdict and asserts subscribe fires exactly once (from the probe) with zero per-task warnings. Pushed in d8cbf6c.

File: packages/client/src/backends/openclaw.test.ts [hunk 5]
```diff
@@ -1638,4 +1638,269 @@ test('discovery skipped when configured URL is remote (non-loopback)', async ()
...
+
+test('resolveCapabilities: returns empty override when gateway is unreachable', async () => {
+  const warnings: string[] = [];
+  const originalWarn = console.warn;
+  console.warn = (...args: unknown[]) => {
+    warnings.push(args.map(String).join(' '));
+  };
+  try {
+    const backend = createOpenclawBackend({
+      url: 'ws://127.0.0.1:1', // port 1 is almost never listening
```
[the remark this answers is not in the document]
Comment (longfin) [reply packages/client/src/backends/openclaw.test.ts]: Fixed — replaced port 1 with `pickUnusedLoopbackPort()` that binds to port 0 on loopback, reads the assigned ephemeral port, closes the server, and hands that number to the test. ECONNREFUSED is now deterministic regardless of what the CI host happens to listen on. Pushed in 5c298d9.

File: packages/client/src/client.ts [hunk 6]
```diff
@@ -37,19 +50,73 @@ export class Client {
...
+        ws.send(
+          encodeFrame({
+            type: 'hello',
+            agentId: this.opts.agentId,
+            agentCard,
+            version: PROTOCOL_VERSION,
+            token: this.opts.token,
+          }),
+        );
       });
```
[the remark this answers is not in the document]
Comment (longfin) [reply packages/client/src/client.ts]: Fixed — `Client.resolveEffectiveCard()` now races the probe against a `probeDeadlineMs` option (default 3000 ms, user-overridable via `ClientOptions.probeDeadlineMs`). On timeout we warn and fall back to the declared card, so even a hung/10s-handshake-timeout backend probe cannot push hello past the server's 10s deadline. 3s leaves ~7s headroom. Late probe results are discarded; on a subsequent bridge reconnect the cached promise has already resolved to the declared card, so we do not double-race. Pushed in 5c298d9.

File: packages/client/src/client.ts [hunk 7]
```diff
@@ -37,19 +58,86 @@ export class Client {
...
+      const timeoutPromise = new Promise<typeof TIMEOUT>((resolve) => {
+        const t = setTimeout(() => resolve(TIMEOUT), deadlineMs);
+        t.unref?.();
+      });
+      const probePromise = probe.call(this.opts.backend).catch((err: unknown) => {
+        console.warn(
+          `[client] backend capability probe threw (${err instanceof Error ? err.message : String(err)}); using declared card capabilities`,
+        );
+        return null;
+      });
```
[the remark this answers is not in the document]
Comment (longfin) [reply packages/client/src/client.ts]: Fixed — wrapped the probe call in `Promise.resolve().then(() => probe.call(...))` so a sync throw from a non-async implementation becomes a promise rejection handled by the existing `.catch`. Also added a defensive `.catch` on the `ws.on('open')` chain that falls back to the declared card if the promise somehow still rejects, so hello is always sent. Pushed in 1e4bd26.

File: packages/client/src/client.ts [hunk 8]
```diff
@@ -37,19 +58,86 @@ export class Client {
...
+      this.effectiveCardPromise = Promise.resolve(base);
+      return this.effectiveCardPromise;
+    }
+    const deadlineMs = this.opts.probeDeadlineMs ?? DEFAULT_PROBE_DEADLINE_MS;
+    this.effectiveCardPromise = (async () => {
+      const TIMEOUT = Symbol('probe-timeout');
+      const timeoutPromise = new Promise<typeof TIMEOUT>((resolve) => {
+        const t = setTimeout(() => resolve(TIMEOUT), deadlineMs);
+        t.unref?.();
+      });
```
[the remark this answers is not in the document]
Comment (longfin) [reply packages/client/src/client.ts:76]: Fixed — `clearTimeout(timer)` in a `finally` around the `Promise.race` so a fast probe releases the pending callback immediately instead of letting it sit armed for up to `deadlineMs`. The existing `unref()` still covers the exit-path case. Pushed in 1e4bd26.

File: packages/client/src/backends/openclaw.test.ts [hunk 9]
```diff
@@ -1,8 +1,34 @@
...
 import { createServer } from 'node:http';
+import { createServer as createNetServer } from 'node:net';
 import type { AddressInfo } from 'node:net';
 import WebSocket, { WebSocketServer } from 'ws';
+
+// Bind a net server to an ephemeral port, record the port, then close the
+// server. The port is now reliably free on this host for the remainder of
+// the test — a subsequent connect attempt gets ECONNREFUSED immediately
+// instead of racing against whatever may happen to be listening on a
+// hard-coded port (e.g. port 1 can be forwarded in some CI environments).
```
[the remark this answers is not in the document]
Comment (longfin) [reply packages/client/src/backends/openclaw.test.ts]: Fixed — reworded the docstring to not overstate the guarantee. Now it explicitly calls out the TOCTOU window (another process could bind between `close()` and our connect) and frames this as "overwhelmingly likely ECONNREFUSED", not "deterministic". Pushed in 1e4bd26.
